# Generated by Django 4.2.7 on 2024-07-25 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0003_rename_country_code_country_code'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authy.country'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authy.state'),
        ),
        migrations.AlterField(
            model_name='nok',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authy.state'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
