# Generated by Django 4.2.7 on 2024-07-22 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=3, unique=True)),
                ('phone_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='state',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='state',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='state',
            name='state_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authy.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authy.state')),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authy.country'),
        ),
    ]
