# Generated by Django 4.2.7 on 2024-07-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_country_remove_state_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country_code',
            new_name='code',
        ),
    ]
